/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author manad
 */
public class CancelTicket extends javax.swing.JFrame {

    /**
     * Creates new form BookTicket
     */
    public static String Name;

    public CancelTicket(String name) {
        initComponents();
        showTableData();
        Name = name;
        //Name=name;
    }

    public CancelTicket() {
        initComponents();
        showTableData();
        //Name=name;
    }

    private static long daysBetween(Date one, Date two) {
        long difference = (one.getTime() - two.getTime()) / 86400000;
        return Math.abs(difference);
    }

     public boolean isvalid(int id) {
        String sql1 = "select * from Transactions where id = ?";
        boolean check=false;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:mysql://" + "localhost" + ":"
                    + "3306" + "/" + "Sams" + "?" + "user=" + "root" + "&password=" + "manad");

            System.out.println("Connected to server");

            PreparedStatement pst1 = conn.prepareStatement(sql1);
            pst1.setInt(1, id);
           
            ResultSet rs1 = pst1.executeQuery();
            rs1.first();
            
            check=true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return check;

    }
//Read more: http://javarevisited.blog//spot.com/2015/07/how-to-find-number-of-days-between-two-dates-in-java.html#ixzz59tDxUPgb 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        idfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cancel Ticket");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Cancel Ticket");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("Show Log");

        jButton1.setText("Cancel Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Transaction ID");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/logo_small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(262, 262, 262))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//          
//        String name=namefield.getText();
//        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
//          
//        String date = dateFormat.format(datefield.getDate()); 
//        //String date= "date";
//        String slot=(String)slotfield.getSelectedItem();
//        //int totalseat=Integer.parseInt(seatfield.getText());
//        String type=(String)typefield.getSelectedItem();
//        
        int id = Integer.parseInt(idfield.getText());

        String insertStr = "";
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:mysql://" + "localhost" + ":"
                    + "3306" + "/" + "Sams" + "?" + "user=" + "root" + "&password=" + "manad");

            System.out.println("Connected to server");

            int b = 0, c = 0;

            // String sql = "select * from  Showlog where date = ? and slot = ?";
            String sql = "select * from  Transactions where id = ?";

//         insertStr= "insert into Show (name, date, slot, totalseat, seatbooked) values("
//                 +quotate(name)+","
//                    +quotate(date)+","
//                    +quotate(slot)+","
//                  +totalseat+","
//                 +b 
//                 +")";
            PreparedStatement pst1 = conn.prepareStatement(sql);
            pst1.setInt(1, id);
            // pst1.setString(2, slot);
            ResultSet rs1 = pst1.executeQuery();
            //rs1.first();

            if (rs1.next()) {

                String date = rs1.getString("showdate");

                Date date1 = new SimpleDateFormat("dd-MM-yyyy").parse(date);
                //System.out.println(date+"\t"+date1); 

                Date date2 = new Date();
                //System.out.println(date1+"\t"+date2+"\t" +daysBetween(date1,date2));
                long difference = daysBetween(date1, date2);
                String slot = rs1.getString("showslot");
                int price = rs1.getInt("amount");
                String name = rs1.getString("showname");
                String performedby = rs1.getString("performedby");

                System.out.println("reached2");
                System.out.println("reached1");

                int penalty = 0;

                if (difference >= 3) {
                    penalty = 5;
                }
                if (difference == 2 || difference == 1) {
                    penalty = 15;
                }

                if (difference < 1) {
                    penalty = price / 2;
                }

                price = price - penalty;

                String sql1 = "DELETE FROM Transactions WHERE id =?";

                PreparedStatement pst = conn.prepareStatement(sql1);
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cancelled successfully");

                String sql2 = "UPDATE Showlog SET earnings=earnings-" + price + " WHERE date=? and slot=?";
// con = DriverManager.getConnection("jdbc:mysql://localhost/idusjavanew","root","");
                PreparedStatement pst2 = conn.prepareStatement(sql2);
                //pst.setString(4, Rollno.getText());
                pst2.setString(1, date);
                pst2.setString(2, slot);
                //pst.setString(3,namefield.getText());
                pst2.executeUpdate();

                String sql3 = "UPDATE Showlog SET seatsbooked = seatsbooked-1 WHERE date=? and slot=?";
// con = DriverManager.getConnection("jdbc:mysql://localhost/idusjavanew","root","");
                PreparedStatement pst3 = conn.prepareStatement(sql3);
                //pst.setString(4, Rollno.getText());
                pst3.setString(1, date);
                pst3.setString(2, slot);
                //pst.setString(3,namefield.getText());
                pst3.executeUpdate();
                JOptionPane.showMessageDialog(null, "updated successfully");

                dispose();
                CancelTicket a = new CancelTicket();
                a.setVisible(true);
                //spose();

//            commentLabel.setText("1 row inserted");
                //getContentPane().removeAll();
                //initComponents();
                conn.close();

                deleteReceipt x = new deleteReceipt(id, name, date, slot, price, performedby);
                x.setVisible(true);
                JOptionPane.showMessageDialog(null, "A penalty of Rs." + penalty + " has been charged as cancellation has been done " + difference + " days before the show");

            } else {
                JOptionPane.showMessageDialog(null, "ID invalid");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        SalesPerson a = new SalesPerson(Name);
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void showTableData() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://" + "localhost" + ":"
                    + "3306" + "/" + "Sams" + "?" + "user=" + "root" + "&password=" + "manad");

            System.out.println("Connected to server");
            String sql = "SELECT * FROM Showlog";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
